### ISSUE TITLE
Unable to parse singer METRICs

### ISSUE THREAD

**Issue by aphethean1** [Matatika/tap-google-sheets#18]
## Background
Taps can output singer METRIC messages.  These are output to stderr, while RECORD messages are output to stdout and intended to be consumed by a target.  i.e. tap -> target.

Monitoring on stderr can parse these METRIC messages and turn them into useful pipeline monitoring.

## Additional information
Error parsing json {:source=>"raw_metric", :raw=>"{'type': 'counter', 'metric': 'record_count', 'value': 4, 'tags': {'stream': 'import_runner_google_sheet'}}", :exception=>#<LogStash::Json::ParserError: Unexpected character (''' (code 39)): was expecting double-quote to start field name

## Proposed fix
For this tap the fix is simple.  Bump the SDK version to a release with this change:  https://github.com/meltano/sdk/commit/9d6a48a2507900db2e13d60b329d19aeac422783

**Comment by ReubenFrankel** [comment]
This is an issue in our catalog, since we are currently pinned to [`v0.3.0`](https://github.com/Matatika/tap-google-sheets/releases/tag/v0.3.0) which [uses SDK version `0.4.5`](https://github.com/Matatika/tap-google-sheets/blob/53edd20eef9a8765e004a1e434247017b2fe9955/pyproject.toml#L15). The [current SDK version used is `0.33.0`](https://github.com/Matatika/tap-google-sheets/blob/c74fa91934a30f882942dc4347fc14d0e888cbff/pyproject.toml#L15), so we should make a new release (`v0.4.0`) and bump the pinned version in the catalog.

**Comment by ReubenFrankel** [comment]
[`v0.4.0` release](https://github.com/Matatika/tap-google-sheets/releases/tag/v0.4.0)
